INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C.1.1','PRUEBA LISTAS EXTERNAS','0','C.1.1.xml', 0);

INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.1','Areas de prestación de servicio','0','C1.1.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.2','Interconexión','0','C1.2.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.3','Redes e infraestructura','0','C1.3.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.4','Accesos disponibles','0','C1.4.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.5','Accesos operativos','0','C1.5.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.6','Clientes operativos (modalidad de contratación)','0','C1.6.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.7','Clientes operativos (segmentación)','0','C1.7.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.8','Clientes operativos (abonos)','0','C1.8.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.9','Tráfico I (llamadas)','0','C1.9.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.17','Calidad de servicio/facturación','0','C1.17.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.18','Calidad de servicio/reclamos','0','C1.18.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.19','Calidad de servicio/atención personalizada','0','C1.19.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.21','Calidad de servicio/atención web','0','C1.21.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.22','Tarifas/precio vigente','0','C1.22.xml', 0);

INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.23','Tarifas/precio minuto de comunicacion telefonia fija','0','C1.23.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.26','Tarifas/planes','0','C1.26.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.29','Ingresos/totales telefonia local por provincia','0','C1.29.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.30','Ingresos/instalacion de linea','0','C1.30.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.31','Ingresos/abono telefonia basica','0','C1.31.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.32','Ingresos/servicios adicionales','0','C1.32.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.33','Ingresos/servicios especiales','0','C1.33.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.34','Ingresos/trafico horario normal','0','C1.34.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.35','Ingresos/trafico horario reducido','0','C1.35.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.36','Ingresos/larga distancia nacional horario normal','0','C1.36.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.37','Ingresos/larga distancia nacional horario reducido','0','C1.37.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.38','Ingresos/larga distancia internacional horario normal','0','C1.38.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.39','Ingresos/larga distancia internacional horario reducido','0','C1.39.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.43','Ingresos interconexion a la red fija - local a vinculadas','0','C1.43.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.46','Gastos en Personal','0','C1.46.xml', 0);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version) VALUES ('C1.48','Costos interconexion','0','C1.48.xml', 0);