INSERT INTO xsl(id, nombre, archivo, xlsversion, version) VALUES (1, 'Para uso de la CNC','formCnc.xsl', 'V1.0', 0);

-- ANEXO C --
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.1','Áreas de prestación de servicios','C1.001-V001-MAY13','C1.1.xml', 0, 1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.2','Interconexión','C1.002-V001-MAY13','C1.2.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.3','Redes e Infraestructura','C1.003-V001-MAY13','C1.3.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.4','Accesos Disponibles','C1.004-V001-MAY13','C1.4.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.5','Accesos Operativos','C1.005-V001-MAY13','C1.5.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.6','Clientes operativos (modalidad de contratación)','C1.006-V001-MAY13','C1.6.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.7','Clientes operativos (segmentación)','C1.007-V001-MAY13','C1.7.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.8','Clientes operativos (abonos)','C1.008-V001-MAY13','C1.8.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.9','Tráfico I (llamadas)','C1.009-V001-MAY13','C1.9.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.10','Tráfico III (cantidad de llamadas)','C1.010-V001-MAY13','C1.10.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.11','Tráfico I (en minutos)','C1.011-V001-MAY13','C1.11.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.12','Tráfico II (minutos)','C1.012-V001-MAY13','C1.12.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.13','Tráfico III (en minutos)','C1.013-V001-MAY13','C1.13.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.14','Tráfico hacia móviles (minutos)','C1.014-V001-MAY13','C1.14.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.15','Tráfico hacia móviles (llamadas)','C1.015-V001-MAY13','C1.15.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.16','Calidad del servicio / Ratios','C1.016-V001-MAY13','C1.16.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.17','Calidad de servicio / Facturación','C1.017-V001-MAY13','C1.17.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.18','Calidad de servicio / Reclamos','C1.018-V001-MAY13','C1.18.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.19','Calidad de servicio / Atención personalizada','C1.019-V001-MAY13','C1.19.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.20','Calidad de servicio / Atención telefónica','C1.020-V001-MAY13','C1.20.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.21','Calidad de servicio / Atención web','C1.021-V001-MAY13','C1.21.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.22','Tarifas / Precio vigente','C1.022-V001-MAY13','C1.22.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.23','Tarifas / Precio minuto de comunicación telefonía fija','C1.023-V001-MAY13','C1.23.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.24','Tarifas / Precio minuto servicios especiales','C1.024-V001-MAY13','C1.24.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.25','Tarifas / Precio servicios adicionales','C1.025-V001-MAY13','C1.25.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.26','Tarifas / Planes','C1.026-V001-MAY13','C1.26.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.27','Tarifas / Planes líneas restringidas','C1.027-V001-MAY13','C1.27.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.28','Ingresos','C1.028-V001-MAY13','C1.28.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.29','Ingresos / Totales telefonía local por provincia','C1.029-V001-MAY13','C1.29.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.30','Ingreso / Instalación de líneas','C1.030-V001-MAY13','C1.30.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.31','Ingresos / Abonos telefonía básica','C1.031-V001-MAY13','C1.31.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.32','Ingresos / Servicios adicionales','C1.032-V001-MAY13','C1.32.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.33','Ingresos / Servicios especiales','C1.033-V001-MAY13','C1.33.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.34','Ingresos / Tráfico horario normal','C1.034-V001-MAY13','C1.34.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.35','Ingresos / Tráfico horario reducido','C1.035-V001-MAY13','C1.35.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.36','Ingresos / Larga distancia nacional horario normal','C1.036-V001-MAY13','C1.36.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.37','Ingresos / Larga distancia nacional horario reducido','C1.037-V001-MAY13','C1.37.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.38','Ingresos / Larga distancia internacional horario normal','C1.038-V001-MAY13','C1.38.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.39','Ingresos / Larga distancia internacional horario reducido','C1.039-V001-MAY13','C1.39.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.40','Ingresos interconexión a la red fija - local a 3°','C1.040-V001-MAY13','C1.40.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.41','Ingresos interconexión a la red fija - larga distancia nacional a 3°','C1.041-V001-MAY13','C1.41.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.42','Ingresos interconexión a la red fija - internacional a 3°','C1.042-V001-MAY13','C1.42.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.43','Ingresos interconexión a la red fija - local a vinculadas','C1.043-V001-MAY13','C1.43.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.44','Ingresos interconexión a la red fija - LDN a vinculadas','C1.044-V001-MAY13','C1.44.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.45','Ingresos interconexión a la red fija - LDI a vinculadas','C1.045-V001-MAY13','C1.45.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.46','Gastos en Personal','C1.046-V001-MAY13','C1.46.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.47','Gastos y Costos','C1.047-V001-MAY13','C1.47.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.48','Costos interconexión','C1.048-V001-MAY13','C1.48.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.49','Personal ocupado','C1.049-V001-MAY13','C1.49.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.50','Inversiones','C1.050-V001-MAY13','C1.50.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.51','Comercio Exterior','C1.051-V001-MAY13','C1.51.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.52','Rentas','C1.052-V001-MAY13','C1.52.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.53','Financiamiento SU / Subsidios','C1.053-V001-MAY13','C1.53.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C1.54','Observaciones','C1.054-V001-MAY13','C1.54.xml', 0,1);

-- ANEXO D --

INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.1','Áreas de prestación de servicios','D1.001-V001-MAY13','D1.1.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.2','Interconexión','D1.002-V001-MAY13','D1.2.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.3','Redes e Infraestructura','D1.003-V001-MAY13','D1.3.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.4','Accesos','D1.004-V001-MAY13','D1.4.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.5','Clientes','D1.005-V001-MAY13','D1.5.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.6','Tráfico I (minutos)','D1.006-V001-MAY13','D1.6.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.7','Tráfico II (minutos)','D1.007-V001-MAY13','D1.7.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.8','Tráfico III (minutos)','D1.008-V001-MAY13','D1.8.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.9','Tráfico IV (minutos)','D1.009-V001-MAY13','D1.9.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.10','Tráfico V (llamadas)','D1.010-V001-MAY13','D1.10.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.11','Tráfico VI (llamadas)','D1.011-V001-MAY13','D1.11.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.12','Tráfico hacia Redes fijas I (minutos)','D1.012-V001-MAY13','D1.12.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.13','Tráfico hacia Redes fijas II (llamadas)','D1.013-V001-MAY13','D1.13.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.14','Trafico hacia Redes móviles I (minutos)','D1.014-V001-MAY13','D1.14.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.15','Tráfico hacia Redes móviles II (llamadas)','D1.015-V001-MAY13','D1.15.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.16','Tráfico de datos','D1.016-V001-MAY13','D1.16.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.17','Roaming (minutos)','D1.017-V001-MAY13','D1.17.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.18','Interconexión (minutos)','D1.018-V001-MAY13','D1.18.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.19','Mensajes','D1.019-V001-MAY13','D1.19.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.20','Calidad del servicio / Ratios','D1.020-V001-MAY13','D1.20.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.21','Calidad del servicio / Facturación','D1.021-V001-MAY13','D1.21.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.22','Calidad del servicio / Reclamos','D1.022-V001-MAY13','D1.22.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.23','Calidad del servicio / Atención personalizada','D1.023-V001-MAY13','D1.23.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.24','Calidad del servicio / Atención telefónica','D1.024-V001-MAY13','D1.24.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.25','Calidad del Servicio / Atención web','D1.025-V001-MAY13','D1.25.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.26','Tasas generales','D1.026-V001-MAY13','D1.26.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.27','Tarifas / Planes pospago - mixto','D1.027-V001-MAY13','D1.27.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.28','Tarifas / Planes prepago','D1.028-V001-MAY13','D1.28.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.29','Tarifas / Roaming - LDN','D1.029-V001-MAY13','D1.29.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.30','Tarifas LDI','D1.030-V001-MAY13','D1.30.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.31','Tarifas / Planes internet móvil','D1.031-V001-MAY13','D1.31.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.32','Tarifas / Servicios adicionales','D1.032-V001-MAY13','D1.32.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.33','Ingresos prestación de servicios / Abonos telefonía móvil','D1.033-V001-MAY13','D1.33.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.34','Ingresos prestación de servicios / Tráfico telefonía móvil','D1.034-V001-MAY13','D1.34.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.35','Ingresos Interconexión','D1.035-V001-MAY13','D1.35.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.36','Otros ingresos','D1.036-V001-MAY13','D1.36.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.37','Ingresos por Provincia','D1.037-V001-MAY13','D1.37.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.38','Gastos en Personal','D1.038-V001-MAY13','D1.38.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.39','Gastos y Costos','D1.039-V001-MAY13','D1.39.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.40','Costos de interconexión','D1.040-V001-MAY13','D1.40.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.41','Personal ocupado','D1.041-V001-MAY13','D1.41.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.42','Inversiones','D1.042-V001-MAY13','D1.42.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.43','Comercio exterior','D1.043-V001-MAY13','D1.43.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.44','Rentas','D1.044-V001-MAY13','D1.44.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.45','Financiamiento SU / Subsidios','D1.045-V001-MAY13','D1.45.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('D1.46','Observaciones','D1.046-V001-MAY13','D1.46.xml', 0,1);

-- Anexo C2 --
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C2.1','Áreas de prestación de servicios','C2.001-V001-MAY13','C2.1.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C2.2','Provisión de líneas','C2.002-V001-MAY13','C2.2.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C2.3','Telefonía pública','C2.003-V001-MAY13','C2.3.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C2.4','Tarifa / precio minuto de comunicación telefonía pública','C2.004-V001-MAY13','C2.4.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C2.5','Ingresos','C2.005-V001-MAY13','C2.5.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C2.6','Ingresos por provincia','C2.006-V001-MAY13','C2.6.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('C2.7','Observaciones','C2.007-V001-MAY13','C2.7.xml', 0,1);

-- Anexo G --
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('G1.1','Áreas de prestación de servicios','G1.001-V001-MAY13','G1.1.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('G1.2','Redes e infrasestructura','G1.002-V001-MAY13','G1.2.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('G1.3','Clientes operativos','G1.003-V001-MAY13','G1.3.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('G1.4','Observaciones','G1.004-V001-MAY13','G1.4.xml', 0,1);

-- Anexo H2 --
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H2.1','Áreas de prestación de servicios','H2.001-V001-MAY13','H2.1.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H2.2','Provisión de líneas','H2.002-V002-MAY13','H2.2.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H2.3','Telefonía pública','H2.003-V003-MAY13','H2.3.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H2.4','Tarifa / Precio minuto de comunicación telefonía pública','H2.004-V001-MAY13','H2.4.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H2.5','Ingresos','H2.005-V001-MAY13','H2.5.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H2.6','Ingresos por provincia','H2.001-V006-MAY13','H2.6.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H2.7','Observaciones','H2.007-V001-MAY13','H2.7.xml', 0,1);

-- Anexo F --
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.1','Accesos Públicos','F1.001-V001-MAY13','F1.1.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.2','Interconexión','F1.002-V001-MAY13','F1.2.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.3','Redes e infraestructura','F1.003-V001-MAY13','F1.3.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.4','Accesos Públicos','F1.004-V001-MAY13','F1.4.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.5','Accesos modalidad de pago','F1.005-V001-MAY13','F1.5.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.6','Clientes servicio tecnología','F1.006-V001-MAY13','F1.6.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.7','Clientes Velocidad','F1.007-V001-MAY13','F1.7.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.8','Tráfico','F1.008-V001-MAY13','F1.8.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.9','Tráfico Internacional','F1.009-V001-MAY13','F1.9.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.10','Calidad de servicio / Ratios','F1.010-V001-MAY13','F1.10.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.11','Calidad de servicio / Facturación','F1.011-V001-MAY13','F1.11.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.12','Calidad de servicio / Reclamo','F1.012-V001-MAY13','F1.12.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.13','Calidad de servicio / Atención personalizada','F1.013-V001-MAY13','F1.13.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.14','Calidad de servicio / Atención telefónica','F1.014-V001-MAY13','F1.14.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.15','Calidad de servicio / Atención web','F1.015-V001-MAY13','F1.15.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.16','Tarifas','F1.016-V001-MAY13','F1.16.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.17','Tasa de interés','F1.017-V001-MAY13','F1.17.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.18','Planes / Tarifa plana','F1.018-V001-MAY13','F1.18.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.19','Planes / Otros','F1.019-V001-MAY13','F1.19.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.20','Planes combinaciones con otros servicios','F1.020-V001-MAY13','F1.20.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.21','Ingresos por velocidad','F1.021-V001-MAY13','F1.21.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.22','Ingresos por provincia','F1.022-V001-MAY13','F1.22.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.23','Gastos','F1.023-V001-MAY13','F1.23.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.24','Gastos y Costos','F1.024-V001-MAY13','F1.24.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.25','Otros Costos','F1.025-V001-MAY13','F1.25.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.26','Personal','F1.026-V001-MAY13','F1.26.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.27','Inversiones','F1.027-V001-MAY13','F1.27.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.28','Comercio exterior','F1.028-V001-MAY13','F1.28.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.29','Rentas','F1.029-V001-MAY13','F1.29.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.30','Financiamiento SU / Subsidios','F1.030-V001-MAY13','F1.30.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('F1.31','Observaciones','F1.031-V001-MAY13','F1.31.xml', 0,1);

-- Anexo E --
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.1','Áreas de prestación de servicio','E1.001-V001-MAY13','E1.1.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.2','Interconexión','E1.002-V001-MAY13','E1.2.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.3','Redes e Infraestructura','E1.003-V001-MAY13','E1.3.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.4','Accesos','E1.004-V001-MAY13','E1.4.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.5','Clientes','E1.005-V001-MAY13','E1.5.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.6','Tráfico I en minutos','E1.006-V001-MAY13','E1.6.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.7','Tráfico II en minutos','E1.007-V001-MAY13','E1.7.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.8','Tráfico III en llamadas','E1.008-V001-MAY13','E1.8.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.9','Tráfico III (# Llamadas)','E1.009-V001-MAY13','E1.9.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.10','Tráfico hacia Redes fijas II (llamadas)','E1.010-V001-MAY13','E1.10.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.11','Tráfico hacia Redes móviles I (minutos)','E1.011-V001-MAY13','E1.11.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.12','Tráfico hacia Redes móviles II (# Llamadas)','E1.012-V001-MAY13','E1.12.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.13','Tráfico de datos','E1.013-V001-MAY13','E1.13.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.14','Roaming (minutos)','E1.014-V001-MAY13','E1.14.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.15','Interconexión (minutos)','E1.015-V001-MAY13','E1.15.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.16','Mensajes','E1.016-V001-MAY13','E1.16.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.17','Calidad del servicio / Ratios','E1.017-V001-MAY13','E1.17.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.18','Calidad de servicio / Facturación','E1.018-V001-MAY13','E1.18.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.19','Calidad de servicio / Reclamos','E1.019-V001-MAY13','E1.19.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.20','Calidad de servicio / Atención personalizada','E1.020-V001-MAY13','E1.20.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.21','Calidad del servicio / Atención telefónica','E1.021-V001-MAY13','E1.21.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.22','Calidad del servicio / Atención web','E1.022-V001-MAY13','E1.22.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.23','Tasas generales','E1.023-V001-MAY13','E1.23.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.24','Tarifas / Planes pospago - mixto','E1.024-V001-MAY13','E1.24.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.25','Tarifas / Planes prepago','E1.025-V001-MAY13','E1.25.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.26','Tarifas / Roaming - LDN','E1.026-V001-MAY13','E1.26.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.27','Tarifas LDI','E1.027-V001-MAY13','E1.27.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.28','Tarifas / Planes internet móvil','E1.028-V001-MAY13','E1.28.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.29','Tarifas / Servicios adicionales','E1.029-V001-MAY13','E1.29.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.30','Ingresos prestación de servicios / Abonos','E1.030-V001-MAY13','E1.30.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.31','Ingresos prestación de servicios / Tráfico','E1.031-V001-MAY13','E1.31.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.32','Ingresos interconexión','E1.032-V001-MAY13','E1.32.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.33','Otros ingresos','E1.033-V001-MAY13','E1.33.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.34','Ingresos por Provincia','E1.034-V001-MAY13','E1.34.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.35','Gastos I','E1.035-V001-MAY13','E1.35.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.36','Gastos II','E1.036-V001-MAY13','E1.36.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.37','Costos de interconexión','E1.037-V001-MAY13','E1.37.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.38','Personal ocupado','E1.038-V001-MAY13','E1.38.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.39','Inversiones','E1.039-V001-MAY13','E1.39.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.40','Comercio exterior','E1.040-V001-MAY13','E1.40.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.41','Rentas','E1.041-V001-MAY13','E1.41.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.42','Financiamiento SU / Subsidios','E1.042-V001-MAY13','E1.42.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('E1.43','Observaciones','E1.043-V001-MAY13','E1.43.xml', 0,1);


-- Anexo H1 --

INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H1.1','Áreas de prestación de servicios','H1.001-V001-MAY13','H1.1.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H1.2','Interconexión','H1.002-V001-MAY13','H1.2.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H1.3','Redes e Infraestructura','H1.003-V001-MAY13','H1.3.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H1.4','Accesos Disponibles','H1.004-V001-MAY13','H1.4.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H1.5','Accesos Operativos','H1.005-V001-MAY13','H1.5.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H1.6','Clientes I','H1.006-V001-MAY13','H1.6.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H1.7','Tráfico I (# llamadas)','H1.007-V001-MAY13','H1.7.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H1.8','Tráfico II (minutos)','H1.008-V001-MAY13','H1.8.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H1.9','Tráfico hacia Redes Móviles (minutos)','H1.009-V001-MAY13','H1.9.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H1.10','Calidad de servicio / Reclamos','H1.010-V001-MAY13','H1.10.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H1.11','Tarifas / Precio vigente','H1.011-V001-MAY13','H1.11.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H1.12','Precio minuto según Distancia','H1.012-V001-MAY13','H1.12.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H1.13','Precio Números Especiales','H1.013-V001-MAY13','H1.13.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H1.14','Precios / Precios Servicios Adicionales','H1.014-V001-MAY13','H1.14.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H1.15','Planes','H1.015-V001-MAY13','H1.15.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H1.16','Ingresos','H1.016-V001-MAY13','H1.16.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H1.17','Ingresos por provincia','H1.017-V001-MAY13','H1.17.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H1.18','Ingresos interconexión a la red fija','H1.018-V001-MAY13','H1.18.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H1.19','Costos','H1.019-V001-MAY13','H1.19.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H1.20','Costos de interconexión','H1.020-V001-MAY13','H1.20.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H1.21','Personal Ocupado','H1.021-V001-MAY13','H1.21.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H1.22','Inversiones','H1.022-V001-MAY13','H1.22.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('H1.23','Observaciones','H1.023-V001-MAY13','H1.23.xml', 0,1);

-- Anexo I --

INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('I1.1','Áreas de prestación de servicios','I1.001-V001-MAY13','I1.1.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('I1.2','Interconexión','I1.002-V001-MAY13','I1.2.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('I1.3','Redes e Infraestructura','I1.003-V001-MAY13','I1.3.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('I1.4','Accesos','I1.004-V001-MAY13','I1.4.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('I1.5','Clientes','I1.005-V001-MAY13','I1.5.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('I1.6','Tráfico (minutos)','I1.006-V001-MAY13','I1.6.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('I1.7','Tráfico saliente','I1.007-V001-MAY13','I1.7.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('I1.8','Tarifas generales','I1.008-V001-MAY13','I1.8.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('I1.9','Tarifas','I1.009-V001-MAY13','I1.9.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('I1.10','Ingresos prestación de servicios','I1.010-V001-MAY13','I1.10.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('I1.11','Gastos I','I1.011-V001-MAY13','I1.11.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('I1.12','Gastos y Costos','I1.012-V001-MAY13','I1.12.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('I1.13','Personal Ocupado','I1.013-V001-MAY13','I1.13.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('I1.14','Inversiones','I1.014-V001-MAY13','I1.14.xml', 0,1);
INSERT INTO formulario (codigo, nombre, formVersion, archivo, version,xsltransform_id) VALUES ('I1.15','Observaciones','I1.015-V001-MAY13','I1.15.xml', 0,1);
