Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(14,167,'12 de Octubre');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(14,166,'1º de Mayo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(14,161,'2 de Abril');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,43,'25 de Mayo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(13,473,'25 de Mayo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(11,435,'25 de Mayo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(14,400,'25 de Mayo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(10,168,'25 de Mayo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,88,'9 de Julio');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(10,506,'9 de Julio');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(11,466,'9 de Julio');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(4,433,'9 de Julio');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(14,165,'9 de Julio');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(11,74,'Adolfo Alsina');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,442,'Adolfo Alsina');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,5,'Adolfo Gonzales Chaves');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,332,'Aguirre');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(10,482,'Albardon');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,327,'Alberdi');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,102,'Alberti');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,106,'Almirante Brown');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(14,172,'Almirante Brown');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(9,429,'Alumine');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(21,146,'Ambato');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(21,145,'Ancasti');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(21,141,'Andalgala');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(10,474,'Angaco');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(7,447,'Anta');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(21,139,'Antofagasta de la Sierra');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(9,425,'Añelo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(13,397,'Apostoles');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(20,366,'Arauco');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,9,'Arrecifes');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,331,'Atamisqui');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(19,358,'Atreuco');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,36,'Avellaneda');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(11,434,'Avellaneda');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,325,'Avellaneda');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,70,'Ayacucho');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(17,487,'Ayacucho');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,31,'Azul');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,21,'Bahia Blanca');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,110,'Balcarce');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,323,'Banda');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,13,'Baradero');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(11,438,'Bariloche');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(21,143,'Belen');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(4,309,'Belgrano');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,489,'Belgrano');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(17,319,'Belgrano');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(15,253,'Bella Vista');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,115,'Benito Juarez');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,27,'Berazategui');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,16,'Berisso');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(14,171,'Bermejo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(23,299,'Bermejo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(15,254,'Beron de Astrada');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(12,191,'Biedma');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,99,'Bolivar');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,20,'Bragado');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,54,'Brandsen');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(6,341,'Burruyacu');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(7,457,'Cachi');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(7,444,'Cafayate');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(13,396,'Cainguas');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,202,'Calamuchita');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(19,228,'Caleu Caleu');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(10,469,'Calingasta');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,22,'Campana');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(13,398,'Candelaria');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,135,'Cañuelas');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(21,137,'Capayan');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(19,198,'Capital');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(7,391,'Capital');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(21,510,'Capital');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(15,443,'Capital');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,479,'Capital');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,402,'Capital');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(13,270,'Capital');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(20,337,'Capital');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(5,227,'Capital');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(10,367,'Capital');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(6,150,'Capital');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,72,'Capitan Sarmiento');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,93,'Carlos Casares');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,32,'Carlos Tejedor');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,24,'Carmen de Areco');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(4,307,'Caseros');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(4,507,'Castellanos');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,26,'Castelli');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(20,368,'Castro Barros');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(9,419,'Catan LilL');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(19,235,'Catrilo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(10,471,'Caucete');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(7,461,'Cerrillos');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,28,'Chacabuco');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(14,156,'Chacabuco');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(17,490,'Chacabuco');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(19,356,'Chalileo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(20,363,'Chamical');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(19,229,'Chapaleufu');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,82,'Chascomus');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(19,225,'Chical Co');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(6,349,'Chicligasta');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(7,451,'Chicoana');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(20,372,'Chilecito');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(10,472,'Chimbas');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,55,'Chivilcoy');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(9,427,'Chos Malal');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,333,'Choya');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(1,193,'Ciudad Autonoma de Buenos Aires');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(16,211,'Cochinoca');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(9,426,'Collon Cura');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,515,'Colon');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(8,197,'Colon');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,287,'Colon');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(14,170,'Comandante Fernandez');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(13,409,'Concepcion');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(15,273,'Concepcion');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(8,281,'Concordia');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(11,430,'Conesa');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(9,414,'Confluencia');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(19,231,'Conhelo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(4,503,'Constitucion');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,324,'Copo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,123,'Coronel de Marina L. Rosales');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,112,'Coronel Dorrego');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(20,369,'Coronel Felipe Varela');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(17,35,'Coronel Pringles');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,485,'Coronel Pringles');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,113,'Coronel Suarez');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(22,499,'Corpen Aike');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(6,343,'Cruz Alta');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,236,'Cruz del Eje');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(19,355,'Curaco');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(15,255,'Curuzu Cuatia');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(12,186,'Cushamen');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,73,'Daireaux');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(22,496,'Deseado');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(8,292,'Diamante');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(16,218,'Doctor Manuel Belgrano');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,38,'Dolores');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(21,152,'El Alto');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(16,303,'El Carmen');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(11,441,'El Cuy');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(13,412,'Eldorado');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(15,258,'Empedrado');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,41,'Ensenada');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(12,182,'Escalante');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,132,'Escobar');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(15,259,'Esquina');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,3,'Esteban Echeverria');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,98,'Exaltacion de la Cruz');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,64,'Ezeiza');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(6,346,'Famailla');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(20,361,'Famatina');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(8,279,'Federacion');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(8,283,'Federal');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(8,291,'Feliciano');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,315,'Figueroa');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,126,'Florencio Varela');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,104,'Florentino Ameghino');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(12,181,'Florentino Ameghino');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(23,295,'Formosa');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(14,174,'Fray Justo Santa Maria de Oro');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(21,148,'Fray Mamerto Esquiu');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(12,192,'Futaleufu');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(12,178,'Gaiman');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(4,207,'Garay');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(12,183,'Gastre');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,87,'General Alvarado');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(15,47,'General Alvear');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(5,383,'General Alvear');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,252,'General Alvear');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(20,373,'General Angel V. Peñaloza');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,67,'General Arenales');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(20,48,'General Belgrano');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(14,159,'General Belgrano');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,362,'General Belgrano');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(14,164,'General Donovan');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(7,446,'General Guemes');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(14,177,'General Guemes');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,76,'General Guido');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(20,370,'General Juan F. Quiroga');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,50,'General Juan Madariaga');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,51,'General La Madrid');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(20,375,'General Lamadrid');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,69,'General Las Heras');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,52,'General Lavalle');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(4,308,'General Lopez');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(13,407,'General Manuel Belgrano');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(4,502,'General Obligado');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(20,365,'General Ocampo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,14,'General Paz');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(15,262,'General Paz');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(17,493,'General Pedernera');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,122,'General Pinto');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,86,'General Pueyrredon');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(11,237,'General Roca');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,431,'General Roca');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,15,'General Rodriguez');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,128,'General San Martin');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,203,'General San Martin');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(20,374,'General San Martin');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,318,'General Taboada');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,81,'General Viamonte');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,91,'General Villegas');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(17,492,'Gobernador Dupuy');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(5,387,'Godoy Cruz');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(15,260,'Goya');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(6,348,'Graneros');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(7,465,'Grl. Jose de San Martin');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(7,453,'Guachipas');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(8,286,'Gualeguay');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(8,284,'Gualeguaychu');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,25,'Guamini');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(13,401,'Guarani');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,328,'Guasayan');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(19,226,'Guatrache');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(5,384,'Guaymallen');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(22,494,'Guer Aike');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,58,'Hipolito Yrigoyen');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(19,234,'Hucal');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(9,417,'Huiliches');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(16,212,'Humahuaca');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,60,'Hurlingham');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(10,467,'Iglesia');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(13,413,'Iguazu');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(20,154,'Independencia');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(14,360,'Independencia');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(4,311,'Iriondo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(7,458,'Iruya');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,200,'Ischilin');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(8,293,'Islas del Ibicuy');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(15,268,'Itati');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(15,62,'Ituzaingo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,257,'Ituzaingo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(10,475,'Jachal');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,322,'Jimenez');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,37,'Jose C. Paz');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(6,513,'Juan Bautista Alberdi');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,338,'Juan F. Ibarra');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,250,'Juarez Celman');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,6,'Junin');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(17,390,'Junin');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(5,488,'Junin');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(7,454,'La Caldera');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(7,455,'La Candelaria');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(17,505,'La Capital');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(4,491,'La Capital');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(6,350,'La Cocha');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,85,'La Costa');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,129,'La Matanza');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(8,386,'La Paz');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(21,280,'La Paz');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(5,149,'La Paz');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,61,'La Plata');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(7,448,'La Poma');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(7,450,'La Viña');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(9,424,'Lacar');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(22,500,'Lago Argentino');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(22,497,'Lago Buenos Aires');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(23,300,'Laishi');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(12,189,'Languiñeo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,77,'Lanus');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,105,'Laprida');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(4,209,'Las Colonias');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,33,'Las Flores');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(5,382,'Las Heras');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(5,380,'Lavalle');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(15,261,'Lavalle');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(6,509,'Leales');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,65,'Leandro N. Alem');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(13,411,'Leandro N. Alem');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(16,222,'Ledesma');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(14,163,'Libertad');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(14,157,'Libertador General San Martin');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(13,406,'Libertador Grl. San Martin');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(17,486,'Libertador Grl. San Martin');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(19,230,'Lihuel Calel');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(19,351,'Limay Mahuida');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,34,'Lincoln');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,111,'Loberia');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,8,'Lobos');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,121,'Lomas De Zamora');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(9,420,'Loncopue');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,335,'Loreto');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(7,463,'Los Andes');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(9,428,'Los Lagos');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(19,352,'Loventue');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,96,'Lujan');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(5,385,'Lujan de Cuyo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(6,344,'Lules');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(22,498,'Magallanes');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,11,'Magdalena');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(5,78,'Maipu');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,393,'Maipu');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(14,173,'Maipu');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(5,388,'Malargue');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,57,'Malvinas Argentinas');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,84,'Mar Chiquita');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(19,224,'Maraco');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,194,'Marcos Juarez');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,134,'Marcos Paz');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(12,187,'Martires');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(23,296,'Matacos');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(14,160,'Mayor Luis J. Fontana');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(15,264,'Mburucuya');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(15,56,'Mercedes');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,265,'Mercedes');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,103,'Merlo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(7,452,'Metan');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(9,242,'Minas');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,422,'Minas');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,336,'Mitre');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(7,464,'Molinos');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,4,'Monte');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(15,266,'Monte Caseros');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,94,'Monte Hermoso');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(13,405,'Montecarlo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(6,512,'Monteros');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,75,'Moreno');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,330,'Moreno');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,127,'Moron');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,63,'Navarro');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,66,'Necochea');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(8,277,'Nogoya');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(9,416,'Ñorquin');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(11,436,'Ñorquinco');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(14,162,'O'' Higgins');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(13,404,'Obera');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,314,'Ojo de Agua');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,59,'Olavarria');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(7,449,'Oran');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(21,144,'Paclin');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(16,305,'Palpala');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(8,290,'Parana');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(12,188,'Paso de Indios');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(15,276,'Paso de los Libres');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,114,'Patagones');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(23,302,'Patiño');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,30,'Pehuajo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(9,415,'Pehuenches');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,18,'Pellegrini');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,316,'Pellegrini');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,119,'Pergamino');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(11,437,'Pichi Mahuida');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(9,423,'Picun Leufu');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(9,418,'Picunches');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,100,'Pila');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(23,301,'Pilagas');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,131,'Pilar');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(11,432,'Pilcaniyeu');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(23,297,'Pilcomayo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,101,'Pinamar');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(23,298,'Pirane');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,249,'Pocho');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(10,470,'Pocito');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(21,140,'Poman');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(14,169,'Presidencia de la Plaza');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,136,'Presidente Peron');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,245,'Presidente Roque Saenz Peña');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,19,'Puan');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(19,223,'Puelen');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,241,'Punilla');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,79,'Punta Indio');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,329,'Quebrachos');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(19,359,'Quemu Quemu');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,44,'Quilmes');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(14,176,'Quitilipi');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,124,'Ramallo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(23,294,'Ramon Lista');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(19,354,'Rancul');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,107,'Rauch');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(12,476,'Rawson');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(10,190,'Rawson');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(19,232,'Realico');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(16,219,'Rinconada');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(6,508,'Rio Chico');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(22,495,'Rio Chico');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,247,'Rio Cuarto');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(24,340,'Rio Grande');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,334,'Rio Hondo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,240,'Rio Primero');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,239,'Rio Seco');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,196,'Rio Segundo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(12,179,'Rio Senguer');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(7,7,'Rivadavia');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,389,'Rivadavia');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(5,456,'Rivadavia');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,477,'Rivadavia');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(10,313,'Rivadavia');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,321,'Robles');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,68,'Rojas');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,23,'Roque Perez');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(4,501,'Rosario');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(7,459,'Rosario de la Frontera');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(7,460,'Rosario de Lerma');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(20,364,'Rosario Vera Peñaloza');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,10,'Saavedra');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(15,269,'Saladas');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,17,'Saladillo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,312,'Salavina');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,109,'Salliquelo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,71,'Salto');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,244,'San Alberto');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,120,'San Andres de Giles');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(16,439,'San Antonio');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(11,215,'San Antonio');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,40,'San Antonio de Areco');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(20,371,'San Blas de los Sauces');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(7,379,'San Carlos');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(5,462,'San Carlos');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,12,'San Cayetano');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(15,267,'San Cosme');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(4,205,'San Cristobal');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(14,130,'San Fernando');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,153,'San Fernando');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(13,403,'San Ignacio');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,90,'San Isidro');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(4,199,'San Javier');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,504,'San Javier');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(13,408,'San Javier');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(4,206,'San Jeronimo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,195,'San Justo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(4,204,'San Justo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(4,306,'San Lorenzo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(14,175,'San Lorenzo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(15,271,'San Luis del Palmar');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(5,310,'San Martin');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(10,378,'San Martin');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,478,'San Martin');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(4,256,'San Martin');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(15,317,'San Martin');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,95,'San Miguel');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(15,263,'San Miguel');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,42,'San Nicolas');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(16,108,'San Pedro');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(13,410,'San Pedro');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,214,'San Pedro');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(5,392,'San Rafael');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(15,272,'San Roque');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(8,285,'San Salvador');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,133,'San Vicente');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(20,377,'Sanagasta');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(16,29,'Santa Barbara');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(16,221,'Santa Catalina');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(10,480,'Santa Lucia');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,251,'Santa Maria');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(21,142,'Santa Maria');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(21,381,'Santa Rosa');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(5,147,'Santa Rosa');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(7,445,'Santa Victoria');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(15,274,'Santo Tome');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(14,158,'Sargento Cabral');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(12,484,'Sarmiento');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(10,180,'Sarmiento');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,320,'Sarmiento');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(15,275,'Sauce');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(18,326,'Silipica');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(6,511,'Simoca');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,243,'Sobremonte');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,53,'Suipacha');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(16,210,'Susques');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(6,342,'Tafi del Valle');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(6,345,'Tafi Viejo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(8,289,'Tala');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,46,'Tandil');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,118,'Tapalque');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(14,155,'Tapenaga');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(12,185,'Tehuelches');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(12,184,'Telsen');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,238,'Tercero Arriba');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,39,'Tigre');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(16,217,'Tilcara');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(21,138,'Tinogasta');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(19,357,'Toay');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(0,0,'Todo el Pais');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,125,'Tordillo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,117,'Tornquist');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,248,'Totoral');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(6,347,'Trancas');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(19,353,'Trenel');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,2,'Trenque Lauquen');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,97,'Tres Arroyos');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,89,'Tres De Febrero');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,116,'Tres Lomas');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,246,'Tulumba');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(16,216,'Tumbaya');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(5,394,'Tunuyan');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(5,395,'Tupungato');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(10,483,'Ullum');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(3,201,'Union');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(8,288,'Uruguay');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(24,339,'Ushuaia');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(19,233,'Utracan');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(11,440,'Valcheta');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(10,468,'Valle Fertil');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(16,220,'Valle Grande');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(21,151,'Valle Viejo');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(4,208,'Vera');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,45,'Vicente Lopez');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(8,278,'Victoria');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,83,'Villa Gesell');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(8,282,'Villaguay');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,92,'Villarino');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(20,376,'Vinchina');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(16,304,'Yavi');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(6,514,'Yerba Buena');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(9,421,'Zapala');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(2,80,'Zarate');
Insert into p_dpto_partido_id (id_prov, id_dpto_partido, descripcion) values(10,481,'Zonda');
