Insert into maestro_provincias (id_prov, descripcion) values(2,'BUENOS AIRES');
Insert into maestro_provincias (id_prov, descripcion) values(3,'CORDOBA');
Insert into maestro_provincias (id_prov, descripcion) values(4,'SANTA FE');
Insert into maestro_provincias (id_prov, descripcion) values(5,'MENDOZA');
Insert into maestro_provincias (id_prov, descripcion) values(6,'TUCUMAN');
Insert into maestro_provincias (id_prov, descripcion) values(7,'SALTA');
Insert into maestro_provincias (id_prov, descripcion) values(8,'ENTRE RIOS');
Insert into maestro_provincias (id_prov, descripcion) values(9,'NEUQUEN');
Insert into maestro_provincias (id_prov, descripcion) values(10,'SAN JUAN');
Insert into maestro_provincias (id_prov, descripcion) values(11,'RIO NEGRO');
Insert into maestro_provincias (id_prov, descripcion) values(12,'CHUBUT');
Insert into maestro_provincias (id_prov, descripcion) values(13,'MISIONES');
Insert into maestro_provincias (id_prov, descripcion) values(14,'CHACO');
Insert into maestro_provincias (id_prov, descripcion) values(15,'CORRIENTES');
Insert into maestro_provincias (id_prov, descripcion) values(16,'JUJUY');
Insert into maestro_provincias (id_prov, descripcion) values(17,'SAN LUIS');
Insert into maestro_provincias (id_prov, descripcion) values(18,'SANTIAGO DEL ESTERO');
Insert into maestro_provincias (id_prov, descripcion) values(19,'LA PAMPA');
Insert into maestro_provincias (id_prov, descripcion) values(20,'LA RIOJA');
Insert into maestro_provincias (id_prov, descripcion) values(21,'CATAMARCA');
Insert into maestro_provincias (id_prov, descripcion) values(22,'SANTA CRUZ');
Insert into maestro_provincias (id_prov, descripcion) values(23,'FORMOSA');
Insert into maestro_provincias (id_prov, descripcion) values(24,'TIERRA DEL FUEGO');
Insert into maestro_provincias (id_prov, descripcion) values(1,'CIUDAD AUTONOMA DE BUENOS AIRES');
Insert into maestro_provincias (id_prov, descripcion) values(25,'AMBA');
